import argparse
from pathlib import Path

# From session
from utils.neuralnetwork import NeuralNetwork

from utils.load_mnist import load_mnist

from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

def main(data_dir_path, epochs):
    # Load data - load_mnist returns a numpy array
    image, label = load_mnist(data_dir_path)

    # Normalization based on the assumption that the pixel intensity is between 0 and 255
    image = image / 255.0

    # Get number of unique classes for output layer size
    classes = set(label)
    num_classes = len(classes)

    # split data into test and training
    img_train, img_test, label_train, label_test = train_test_split(image, label, random_state=1111, test_size=0.2)

    # convert labels to binary representation
    # This allows us to represent each class as binary values instead of strings
    # since the neuralnetwork cant work with our representation of the labels (0-9)
    label_train = LabelBinarizer().fit_transform(label_train)
    label_test = LabelBinarizer().fit_transform(label_test)

    # specify the neural network structure with 2 small hidden layers
    # each layer is represented in argument-list.
    neural_network = NeuralNetwork([img_train.shape[1], 32, 16, num_classes])

    # fit model for a given number of epochs (5 per default)
    # as we're working with the full dataset, 5 epochs can already be hard to compute
    neural_network.fit(img_train, label_train, epochs=epochs)

    # make predictions on all test images
    label_pred = neural_network.predict(img_test)
    # highest probability label
    label_pred = label_pred.argmax(axis=1)

    # generate metrics from test set prediction for comparison
    classifier_metrics = metrics.classification_report(label_test.argmax(axis=1), label_pred)

    # save metrics as txt file and print in terminal
    with open('output/nn_metrics.txt', 'w') as output:
        output.write(classifier_metrics)

    print(classifier_metrics)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = "a script that trains a neural network on the mnist_784 dataset and generates a metrics report for the classifier")
    parser.add_argument("-d", "--data_dir_path", default = Path('./data'), help = "path to the destination or location of the mnist csv-files generated by load_mnist.py")
    parser.add_argument("-e", "--epochs", default = 5, type = int, help = "number of epochs to train")

    args = parser.parse_args()
    
    main(data_dir_path = args.data_dir_path, epochs = args.epochs)